#!/usr/bin/env perl
sub slurp { 
    local( $/, @ARGV ) = ( wantarray ? $/ : undef, @_ ); 
    return <ARGV>;
}
my ($build, $version, $name, $ext) = @ARGV;

my $content = slurp($name . $ext);
($header, $code) = $content =~ /^\s*(\/\*\*.*?\*\/)\s*(.+?)\s*$/s;

open(FULL, '>' . $build . '/' . $name . '-' . $version . $ext);
print FULL $content;
close(FULL);


open(HEADER, '>' . $build . '/' . $name . '-header' . $ext);
print HEADER $header . "\n";
close(HEADER);

open(CODE, '>' . $build . '/' . $name . '-code' . $ext);
print CODE $code;
close(CODE);

#print $text
#$content = <>;
#($header, $code) = $content =~ /^\s*(\/\*\*.*?\*\/)\s*(.+?)\s*$/s;
#print "writing header to " . $ARGV[0] . "\n";
#print "writing code to " . $ARGV[1] . "\n";
